### ISSUE TITLE
Implement Python support for writing rules

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-policy#98]
Meta issue tracking the following work:

- [ ] Basic support for writing policies in Python #208
- [ ] Warn when accessing unknown property values #209
- [ ] Add support for policy configuration #210
- [ ] Support publishing Python policy packs #211
- [ ] Restructure how Policy plugins work #193

**Comment by joeduffy** [comment]
I am only now realizing policy plugins don't work the way I had thought.

Instead of having a plugin per policy pack, we have a single universal plugin, `pulumi-analyzer-policy`, which loads Node.js program that dynamically loads the desired policy pack.

This seems like it will fundamentally make it difficult to ever support more than just Node.js.

The alternative, which I assumed we were doing, was to use the plugin system to distribute, install, and manage policy packs, and to use the ability to have many versions side-by-side. That would get us multi-language while also aligning with how the rest of the system works.

And yet that's a fairly fundamental change. @justinvp Have you thought much about this? Do you have an alternative in mind that is simpler to get to from where we are?

I hit this because I need to write a policy pack in Go.

**Comment by justinvp** [comment]
I'm going to close this meta-issue since we have smaller issues tracking the reamining work to do here (linked in the description).
